# this action creates an exe with the pyinstaller function within github actions
on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    env:
      tag: v1.0.3
      script: script
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Create Executable
        run: pyinstaller --onefile src/${{ env.script }}.py

      - name: Publish a New Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/${{ env.script }}.exe
          tag: ${{ env.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
